### ISSUE TITLE
macos-arm64 is missing for 1.54.0

### ISSUE THREAD

**Issue by larsgrefer** [sass/dart-sass-embedded#102]
The macos-arm64 variant is missing for 1.54.0.

I build one locally, if someone needs it:

[sass_embedded-1.54.0-macos-arm64.tar.gz](https://github.com/sass/dart-sass-embedded/files/9172881/sass_embedded-1.54.0-macos-arm64.tar.gz)

**Comment by nex3** [comment]
This was broken by our attempted update to releasing native ARM executables, which was in turn broken by  https://github.com/arduino/setup-protoc/pull/26. I'll work on a fix this week.
