### ISSUE TITLE
npm ERR! Downloading dart-sass-embedded release asset

### ISSUE THREAD

**Issue by rp15nov** [sass/dart-sass-embedded#111]
As i am not able to install with angular 14.2.1 version and i am getting below error.
npm ERR! Downloading dart-sass-embedded release asset.
npm ERR! FetchError: request to https://github.com/sass/dart-sass-embedded/releases/download/1.54.4/sass_embedded-1.54.4-windows-x64.zip failed, reason: self signed certificate in certificate chain

**Comment by nex3** [comment]
The latest version of `sass-embedded` uses npm optional dependencies to get its native executables rather than downloading them on the users' systems, so this should go away if you upgrade.
