### ISSUE TITLE
Homebrew tap for Dart SASS Emedded

### ISSUE THREAD

**Issue by merchako** [sass/dart-sass-embedded#119]
Dart SASS Embedded is an important component of a Hugo stack, and it's a mess at the moment figuring out how to assemble it all. Might you consider writing a Homebrew tap to make the installation and configuration process easier on macOS?

Examples of confusion:
 * https://discourse.gohugo.io/t/installing-dart-sass-embedded/32468/10 
 * https://github.com/gohugoio/hugo/issues/8299#issuecomment-1327841933

**Comment by nex3** [comment]
Our intention is to make it easy to distribute the embedded Dart Sass executables _along with_ executables for the embedded host (in this case, Hugo). But I'm not opposed to setting up a tap for this in https://github.com/sass/homebrew-sass using [`cli_pkg`](https://pub.dev/packages/cli_pkg) if someone wants to send a PR.
