### ISSUE TITLE
Unstable release archives

### ISSUE THREAD

**Issue by bep** [sass/dart-sass-embedded#125]
See

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/394382/207367194-56bdbd68-2f9d-41f2-9537-247c5ec1e326.png">

Version 1.56.1 was released in November, yet the archives was updated 15 hours ago.

I'm maintaining Hugo and we compare sha256 sums for these archives before we start using them -- which, not surprisingly, now starts to fail.

Was this a one time thing or do we need to somehow store these archives ourselves?

**Comment by ntkme** [comment]
@bep Details will be announced. Preview is here: https://github.com/sass/sass-site/pull/689

**Comment by bep** [comment]
OK, thanks.
