### ISSUE TITLE
Linux packaging with 1.58.0 and later

### ISSUE THREAD

**Issue by jmooring** [sass/dart-sass-embedded#150]
With v1.57.1 and earlier, the Linux x64 package contained a single executable.

That changed with 1.58.0 and later, making manual installation a bit more complicated for casual users.

Was the change intentional?

**Comment by ntkme** [comment]
It was to workaround https://github.com/dart-lang/sdk/issues/50926 and fix #78.

**Comment by jmooring** [comment]
Thank you for the explanation.
