### ISSUE TITLE
question: Any estimated time for a release?

### ISSUE THREAD

**Issue by bep** [sass/dart-sass-embedded#20]
I maintain Hugo (written in Go), a project that looks forward to replacing the now deprecated LibSASS with embedded Dart Sass.

A "we have no idea" answer is better than nothing, and I totally understand that dates and open source isn't easy.

**Comment by nex3** [comment]
There are beta releases available [on the Releases page](https://github.com/sass/dart-sass-embedded/releases). A stable release will likely be concurrent with the release of the JS Embedded Host, which is planned for Q1 2021.
