### ISSUE TITLE
Custom importer not invoked when CompileRequest.Url points to a real file

### ISSUE THREAD

**Issue by bep** [sass/dart-sass-embedded#24]
I'm not sure if this repo is the right one, but here you go:

* I fill out the `Url` in the request mainly to get a correct source map
* When this `Url` points to an existing file, the custom importers defined is not invoked
* My current workaround is to put a dummy value as a placeholder here and then replace that in the source map I get-

This is tested with beta 5.

```go
message := &embeddedsass.InboundMessage_CompileRequest_{
			CompileRequest: &embeddedsass.InboundMessage_CompileRequest{
				Importers: customImporters,
				Input: &embeddedsass.InboundMessage_CompileRequest_String_{
					String_: &embeddedsass.InboundMessage_CompileRequest_StringInput{
						Source: "@import \"colors;\"",
						Url:    "file:///styles/main.scss",
					},
				},
			},
		}
```

**Comment by nex3** [comment]
If you want to control how imports are resolved relative to the entrypoint file's URL, such as `@import "colors"` here, you need to set the `StringInput.importer` field. (Note though that this is currently bugged; you'll need to wait for https://github.com/sass/dart-sass-embedded/pull/22 to be released for it to work properly, or you'll need to build the project yourself. If you install Dart, you can build it by running `pub get` followed by `pub run grinder pkg-compile-${os}-x64`).
