### ISSUE TITLE
Versionning policy regarding dart-sass

### ISSUE THREAD

**Issue by stof** [sass/dart-sass-embedded#29]
It looks like the binary releases of dart-sass-embedded are bundling a dart-sass release in them (as it is a pub dependency). for now, it looks like the version numbers of dart-sass-embedded are totally decoupled from the dart-sass release. This makes it hard to figure out which version of dart-sass ends up being used (which is relevant for support of sass features).

Wouldn't it make sense to release this repository with a version number synced with the one of dart-sass and ensuring that a new release of dart-sass-embedded is done each time dart-sass gets released ?

**Comment by nex3** [comment]
Yes, once we start releasing stable versions we intend to make the version numbers Dart Sass Embedded and the Node Embedded Host match Dart Sass's version.
