### ISSUE TITLE
Versionning for the implemented protocol

### ISSUE THREAD

**Issue by stof** [sass/dart-sass-embedded#31]
AFAICT, the client-side and server-side implementations of the [embedded protocol](https://github.com/sass/embedded-protocol) need to use the same version of the protocol to be compatible.
It would be great if the dart-sass-embedded executable could report the version of the protocol for which it has been compiled, to make it easier to check for such issues.

**Comment by stof** [comment]
this should probably imply using the latest dart for the embedded-protocol rather than using the latest master though.

**Comment by stof** [comment]
Looking at the details of the protocol itself, it looks like there is a way to access this info through the protocol itself. But it might be helpful to allow running something like `dart-sass-embedded --version` to get the equivalent info than the VersionResponse message

**Comment by stof** [comment]
note that the use case I had in mind for `dart-sass-embedded --version` would be doing checks in packaging scripts or post-install scripts (depending of what is used) regarding the issue of version skew (mentioned in the readme). Requiring the packaging script to use the embedded protocol to get the info would make it more complex that calling something like `dart-sass-embedded --version` or `dart-sass-embedded --protocol-version` or equivalent.

**Comment by stof** [comment]
@nex3 any feedback here ?

Note also that #33 means that the embedded protocol does not expose the info either for now.

**Comment by TheJaredWilcurt** [comment]
In Node you can do `process.versions` and it returns an object
```js
{
  node: '14.15.4',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```

`dart-sass-embedded --versions` could do a similar thing, storing the versions of everything it ships with.

**Comment by stof** [comment]
Well, the embedded protocol already forces the compiler to expose this info (the host can query it through the protocol). This feature request is about an easy way to get that info from the CLI.
