### ISSUE TITLE
Inconsistent packaging of linux-x64 in version 1.0.0-beta.7

### ISSUE THREAD

**Issue by larsgrefer** [sass/dart-sass-embedded#38]
The linux-x64 variant of version 1.0.0-beta.7 is packaged slightly differently than the other packages.

For version 1.0.0-beta.6 all 5 variants were packaged the same way:
 - A dart executable (`sass_embedded/src/dart(.exe)`)
 - A snapshot of dart-sass-embedded (`sass_embedded/src/dart-sass-embedded.snapshot`)
 - A shell script combining both (`sass_embedded/dart-sass-embedded(.bat)`)

For version 1.0.0-beta.7 all variants - except for linux-x64 - are still packaged the same way.
The linux-x64 however does not contain a sass executable nor a `dart-sass-embedded.snapshot` file and instead of the shell script there is just one fully executable binary.

It would be easier for host implementors if all variants were packaged the same way.

**Comment by Awjin** [comment]
This is a byproduct of the first step in a larger move towards packaging executables for all OSes: https://github.com/google/dart_cli_pkg/issues/67. This in-between state should be ok for now, since snapshots and executables are invoked in the same way.

**Comment by nex3** [comment]
The main guarantee we provide is that `sass_embedded/dart-sass-embedded` (possibly with an executable extension of some kind on Windows) will run the compiler. Everything else should be considered an implementation detail.

**Comment by larsgrefer** [comment]
Having only a single "all-in-one" executable for each os/arch combination would be great because it makes the repackaging a lot simpler.

With my current repackaging setup in https://github.com/larsgrefer/dart-sass-java I have to know (and manually extract) all needed files. That's why I stumbled upon this.

**Comment by nex3** [comment]
All-in-one executables are definitely something we'd like to have as well, but OS code signing requirements make them quite difficult to set up and integrate into our release process so I wouldn't hold your breath for them.
