### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Splaktar** [sass/dart-sass-embedded#39]
Is there any documentation for this?

Is there any way to try it with the Angular CLI?

**Comment by jathak** [comment]
This repo is for the embedded compiler, which host languages can embed to compile Sass code, so the readme is focused on implementers who want to embed Dart Sass in another language.

For end users who want to use embedded Sass from Node, you should use [this NPM package](https://www.npmjs.com/package/sass-embedded) in place of the regular compiled-to-JS `sass` package. Note that it is still in beta and under active development, so you may run into issues that you should report [here](https://github.com/sass/embedded-host-node/issues).
