### ISSUE TITLE
Ruby Host Implementation

### ISSUE THREAD

**Issue by ntkme** [sass/dart-sass-embedded#42]
Just want to share that I created a host implementation for ruby: https://github.com/ntkme/embedded-host-ruby 

It can be installed with:

``` sh
gem install sass-embedded
```

Unlike the `scssc-ruby`, the API is made to be close to the JavaScript API, except that for options it uses symbol in snake case instead of string in camel case. E.g. `:indented_syntax` instead of `indentedSyntax`.

``` ruby
require "sass"

Sass.render(file: "style.scss")
```

Example output:

```
irb(main):001:0> require "sass"
=> true
irb(main):002:0> 
irb(main):003:2* Sass.render(
irb(main):004:2*   data: "h1 { color: black; }",
irb(main):005:2*   indented_syntax: false
irb(main):006:0> )
=> {:css=>"h1 {\n  color: black;\n}", :map=>"", :stats=>{:entry=>"data", :start=>1621839779808, :end=>1621839779826, :duration=>18}}
```

**Comment by Awjin** [comment]
Thanks, it's exciting to see a ruby implementation!

**Comment by nex3** [comment]
Heads up @ntkme, there are some breaking changes coming to the protocol soon—I'm planning to fix it to follow the protobuf style guide, but that will involve renaming some fields. Sorry for the churn!

I've filed https://github.com/sass/sass-site/issues/547 to track listing this on the website once we have a stable release of the embedded protocol.

**Comment by ntkme** [comment]
@nex3 Thanks for the heads up.

For the renaming change, do you mean this commit? https://github.com/sass/embedded-protocol/commit/10eb6f47e06d42323335d387b75dc3401a200d46 
If that's the case, I already got it covered.

I'm watching embedded-protocol and I will update if there is any further changes. So no worries.

**Comment by nex3** [comment]
Yep, exactly!
