### ISSUE TITLE
How to install dart-sass-embedded in order to use it in Hugo?

### ISSUE THREAD

**Issue by selfishprimate** [sass/dart-sass-embedded#76]
I just can't figure out how to use this package in order to use Dart Sass with Hugo. Can you help, please?

**Comment by nex3** [comment]
This is a great question for the [Sass StackOverflow community](https://stackoverflow.com/questions/ask?tags=sass)! We try to keep this issue tracker focused on bugs and feature requests that need the core team's attention in particular, while requests for support are usually better handled by the community at large.
