### ISSUE TITLE
How to add this to dart-sass already installed?

### ISSUE THREAD

**Issue by TenSketch** [sass/dart-sass-embedded#81]
Hi,
I'm developing a Hugo website. I have installed both Hugo and Sass thro choco in my windows. 

> hugo version
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended windows/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio

> sass --version
1.49.9

I'm not sure how to add this **_dart-sass-embedded_** to the **dart-sass** already installed?

![image](https://user-images.githubusercontent.com/23096153/160972518-66fcb970-e532-477d-bf82-fadd2fe8645f.png)

![image](https://user-images.githubusercontent.com/23096153/160972657-b3508a4b-e5ad-46e1-96dd-7079eaa675b5.png)

How to add this wrapper ? and to PATH?
In Ubuntu also, I didn't succeed.

https://discourse.gohugo.io/t/extended-hugo-version-is-not-working/37718

**Comment by jathak** [comment]
The embedded compiler is designed to be used by a host library that implements [the embedded protocol](https://github.com/sass/embedded-protocol). You shouldn't download/use it directly.

If you're just running Sass from the command line, you don't need this at all. If you're trying to use the Sass JS API, you can install either the `sass` NPM module (which is compiled to JS) or the `sass-embedded` NPM module (which implements the embedded protocol and will fetch the embedded compiler automatically).
