### ISSUE TITLE
1.52.1 release: `--version` reports 1.51.0

### ISSUE THREAD

**Issue by brycewray** [sass/dart-sass-embedded#87]
I just downloaded 1.52.1 and put the binary in my `$PATH`, but got the following response when I did `dart-sass-embedded --version`:

```bash
{
  "protocolVersion": "1.0.0",
  "compilerVersion": "1.51.0",
  "implementationVersion": "1.51.0",
  "implementationName": "Dart Sass",
  "id": 0
}
```

**Comment by ntkme** [comment]
```
$ wget https://github.com/sass/dart-sass-embedded/releases/download/1.52.1/sass_embedded-1.52.1-linux-x64.tar.gz
$ tar xf sass_embedded-1.52.1-linux-x64.tar.gz
$ cd sass_embedded
$ ./dart-sass-embedded --version
{
  "protocolVersion": "1.0.0",
  "compilerVersion": "1.52.1",
  "implementationVersion": "1.52.1",
  "implementationName": "Dart Sass",
  "id": 0
}
```

Am I missing anything?

**Comment by brycewray** [comment]
> ```
> $ wget https://github.com/sass/dart-sass-embedded/releases/download/1.52.1/sass_embedded-1.52.1-linux-x64.tar.gz
> $ tar xf sass_embedded-1.52.1-linux-x64.tar.gz 
> $ ./dart-sass-embedded --version
> {
>   "protocolVersion": "1.0.0",
>   "compilerVersion": "1.52.1",
>   "implementationVersion": "1.52.1",
>   "implementationName": "Dart Sass",
>   "id": 0
> }
> ```
> 
> Am I missing anything?

Sorry, should’ve mentioned this is `sass_embedded-1.52.1-macos-x64.tar.gz`.

**Comment by ntkme** [comment]
On a mac:

```
$ curl -fsSLo sass_embedded-1.52.1-macos-x64.tar.gz https://github.com/sass/dart-sass-embedded/releases/download/1.52.1/sass_embedded-1.52.1-macos-x64.tar.gz
$ tar -xf sass_embedded-1.52.1-macos-x64.tar.gz
$ cd sass_embedded
$ ./dart-sass-embedded --version
{
  "protocolVersion": "1.0.0",
  "compilerVersion": "1.52.1",
  "implementationVersion": "1.52.1",
  "implementationName": "Dart Sass",
  "id": 0
}
```

**Comment by brycewray** [comment]
Very odd. I’ll try another download. Thanks.

**Edit**: To make sure I wasn’t doing something wrong (even though this is my usual procedure), I used your `curl` and `tar` commands exactly. Still getting the `1.51.0` results I noted earlier. Really strange.

**Comment by ntkme** [comment]
Can you try running it from the current directory as in my previous comment? I suspect you're doing something wrong with PATH.

**Comment by brycewray** [comment]
> Can you try running it from the current directory as in my previous comment? I suspect you're doing something wrong with PATH.

Yes, that works (1.52.1), so something odd has happened to my `$PATH` because, up to now, the procedure I normally follow works without fail. Thanks.

**Later edit**: Apparently, that procedure has been wrong all along. No idea how it worked up to now. Anyway, live and learn.
